name: Deploy to AWS Lambda on Merge

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to AWS Lambda on merge
    steps:
    - uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598 # 2.0.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@b7821147f564527086410e8edd122d89b4b9602f # 1.4.0
      with:
        dotnet-version: 2.1.510
    - name: Setup Nuget CLI
      uses: NuGet/setup-nuget@255f46e14d51fbc603743e2aa2907954463fbeb9 # 1.0.2
    - name: Install dotnet lambda tool
      run: dotnet tool install --global Amazon.Lambda.Tools
    - name: Publish with dotnet lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: >-
        dotnet lambda
        deploy-function MyFunction
        --project-location src/MyFunction
        --function-role TestRole
        --aws-access-key-id $AWS_ACCESS_KEY_ID
        --aws-secret-key $AWS_SECRET_KEY
        --region $AWS_REGION
        --function-publish true
